spring.application.name=hrmtask
server.port=${PORT:8080}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_UNAME}
spring.datasource.password=${DB_PASS}

spring.mail.host=${MAIL_HOST}
spring.mail.port=587
spring.mail.username=${MAIL_ID}
spring.mail.password=${MAIL_PASS}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=${JWT_SECRET}
jwt.access-expiration=900000
jwt.refresh-expiration=604800000
