spring.application.name=hrmtask
server.port=${PORT:8080}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_UNAME}
spring.datasource.password=${DB_PASS}

brevo.api.key=${BREVO_API_KEY}
brevo.from.email=${BREVO_FROM_EMAIL}
brevo.from.name=${BREVO_FROM_NAME:HR Management System}

jwt.secret=${JWT_SECRET}
jwt.access-expiration=900000
jwt.refresh-expiration=604800000
